name: basic_app_security
description: "A basic Jailbreak and Root Detection package for Flutter"
version: 1.0.3

repository: https://github.com/tyypgzl/basic_app_security
issue_tracker: https://github.com/tyypgzl/basic_app_security/issues
homepage: https://tguzel.dev/
topics: ["jailbreak", "root", "security", "flutter"]

environment:
  sdk: ^3.7.2
  flutter: ">=3.29.2"

dependencies:
  flutter:
    sdk: flutter
  
  basic_widgets: ^1.0.6

  root_jailbreak_sniffer: ^1.1.0

dev_dependencies:
  basic_lint: ^1.0.1
  